config/routes.rb
ProMapper::Application.routes.draw do
  resources :categories, :only => [:index]

  get 'import', to: 'jobs#upload'
  post 'import', to: 'jobs#import'

  root :to => 'categories#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name , presence: true
  has_many :jobs
end

app/models/job.rb
require "csv"

class Job < ActiveRecord::Base
  validates :title, :description, :address, :latitude, :longitude , presence: true
  belongs_to :category

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Job.create! row.to_hash
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @jobs = Job.all

    if params['category']
      @jobs = Job.where(category_id: Category.find_by(name: params['category']).id)
    end

    respond_to do |format|
      format.html
      format.json { render :json => @jobs.to_json  }
    end
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def import
    Job.import(params[:file])
    redirect_to root_url, notice:"Jobs imported."
  end

  def upload

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<div class='main-container'>
  <div id='category_selector'>
    <h1 id='title'>ProMapper</h1>

    <form id="category_form">
      <select name="category" id="event" type="dropdown">
        <option value="event" disabled selected autofocus>CATEGORY</option>
        <option value="accounting+finance" >accounting+finance</option>
        <option value="admin/office">admin/office</option>
        <option value="arch/engineering">arch/engineering</option>
        <option value="biotech/science">biotech/science</option>
        <option value="business/mgmt">business/mgmt</option>
        <option value="customer-service">customer-service</option>
        <option value="education">education</option>
        <option value="food/bev/hosp">food/bev/hosp</option>
        <option value="general-labor">general-labor</option>
        <option value="government">government</option>
        <option value="human-resources">human-resources</option>
        <option value="internet-engineers">internet-engineers</option>
        <option value="legal/paralegal">legal/paralegal</option>
        <option value="manufacturing">manufacturing</option>
        <option value="marketing/pr/ad">marketing/pr/ad</option>
        <option value="medical/health">medical/health</option>
        <option value="nonprofit">nonprofit</option>
        <option value="medical/health">medical/health</option>
        <option value="real-estate">real-estate</option>
        <option value="sales/bizdev">sales/bizdev</option>
        <option value="retail/wholesal">retail/wholesale</option>
        <option value="salon/spa/fitness">salon/spa/fitness</option>
        <option value="security">security</option>
        <option value="trade/craft">trade/craft</option>
        <option value="software/qa/dba">software/qa/dba</option>
        <option value="systems/network">systems/network</option>
        <option value="technical-support">technical-support</option>
        <option value="transport">transport</option>
        <option value="tv/film/video">tv/film/video</option>
        <option value="web/info">web/info</option>
        <option value="web/info">web/info-design</option>
        <option value="writing/editing">writing/editing</option>
      </select>
       <input type='submit' id ="submit_button" class='button quiet' value='Search' name='' />
     </form>
    </div>

  <div id="map-canvas"></div>

</div

app/views/jobs/upload.html.erb
<h1>Import Jobs</h1>

<%= form_tag import_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProMapper</title>
  <script src="http://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
  <link href='http://fonts.googleapis.com/css?family=Oswald|Open+Sans' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
</body>
</html>